## Projeto 4
## Aprendizado de Máquina com tarefa de classificação aplicado no dataset  de variedades de trigo

Alunos: Juliany, Raí, Richardson

### Introdução

Três variedades de trigo (Kama, Rosa e Canadian) possuem sementes muito parecidas,
entretanto diferentes. Um grupo de pesquisadores poloneses coletou 70 amostras de cada
tipo e, usando uma técnica particular de raio-X, coletou medidas geométricas destas
sementes, a citar: área, perímetro, compactude, comprimento, largura, coeficiente de
assimetria e comprimento do sulco da semente.

### Características dos atributos

In [104]:
# Módulos utilizados no projeto

import pandas as pd
import numpy as np
import random
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
% matplotlib inline
sns.set()

In [70]:
dataframe = pd.read_csv("../data/seeds_dataset.txt", delim_whitespace = True)
dataframe.head()

area  perimeter  compactness  length_of_kernel  width_of_kernel  \
0  15.26      14.84       0.8710             5.763            3.312   
1  14.88      14.57       0.8811             5.554            3.333   
2  14.29      14.09       0.9050             5.291            3.337   
3  13.84      13.94       0.8955             5.324            3.379   
4  16.14      14.99       0.9034             5.658            3.562   

   asymmetry_coefficient  length_of_kernel_groove  target  
0                  2.221                    5.220       1  
1                  1.018                    4.956       1  
2                  2.699                    4.825       1  
3                  2.259                    4.805       1  
4                  1.355                    5.175       1

### Treinamento

In [75]:
X = dataframe.drop('target', axis=1)
y = dataframe['target']

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [133]:
rate  = [0.01, 0.05]
epoch = 50
a     = [0.5, 2, 3]

max_iter   = [1000, 2000,  2500]
neuron_out = np.arange(1, 15)
neuron_ini = np.arange(1, 15)
activation_functions = ['relu', 'logistic', 'identity']

In [161]:
list_prediction = []

In [164]:
for i in range(5):
    ai  = random.choice(a)
    ni  = random.choice(neuron_ini)
    no  = random.choice(neuron_out)

    nh  = ai*np.sqrt((ni*no))

    activation_i = random.choice(activation)

    parameters = dict([
                    ('max_iter', max_iter),
                    ('hidden_layer_sizes', (no,)),
                    ('learning_rate_init', rate),
                    ('activation', activation_functions)
                ])

    clf = GridSearchCV(MLPClassifier(), parameters, cv = 3)
    clf.fit(X_train, y_train)
    prediction = clf.predict(X_test)

    f1score = f1_score(y_test, prediction, average = 'weighted')
    list_prediction.append([f1score, prediction])

/home/julianyraiol/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/julianyraiol/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/julianyraiol/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [165]:
list_prediction

[[<function sklearn.metrics.classification.f1_score(y_true, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None)>,
  array([1, 2, 3, 2, 3, 2, 3, 3, 1, 3, 3, 1, 1, 2, 2, 3, 1, 1, 2, 1, 3, 1,
         2, 3, 3, 2, 1, 3, 1, 2, 2, 2, 2, 2, 3, 2, 1, 2, 1, 1, 2, 3, 2, 2,
         3, 3, 3, 2, 2, 2, 2, 1, 3, 1, 2, 2, 3, 2, 1, 1, 1, 3, 3])],
 [<function sklearn.metrics.classification.f1_score(y_true, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None)>,
  array([1, 2, 3, 2, 3, 2, 3, 3, 1, 3, 3, 1, 1, 2, 2, 3, 1, 1, 2, 1, 3, 1,
         2, 3, 3, 2, 1, 3, 1, 2, 2, 2, 2, 2, 3, 2, 1, 2, 1, 1, 2, 3, 2, 2,
         3, 3, 3, 2, 2, 2, 2, 1, 3, 1, 2, 2, 3, 2, 1, 1, 1, 3, 3])],
 [<function sklearn.metrics.classification.f1_score(y_true, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None)>,
  array([1, 2, 3, 2, 3, 2, 3, 3, 1, 3, 3, 1, 1, 2, 2, 3, 1, 1, 2, 1, 3, 1,
         2, 3, 3, 2, 1, 3, 1, 2, 2, 2, 2, 2, 3, 2, 1, 2, 1, 1, 2, 3, 2, 2,
         3