## Projeto 4
## Aprendizado de Máquina com tarefa de classificação aplicado no dataset  de variedades de trigo

Alunos: Juliany, Raí, Richardson

### Introdução

Três variedades de trigo (Kama, Rosa e Canadian) possuem sementes muito parecidas,
entretanto diferentes. Um grupo de pesquisadores poloneses coletou 70 amostras de cada
tipo e, usando uma técnica particular de raio-X, coletou medidas geométricas destas
sementes, a citar: área, perímetro, compactude, comprimento, largura, coeficiente de
assimetria e comprimento do sulco da semente.

### Características dos atributos

In [1]:
# Módulos utilizados no projeto

import pandas as pd
import numpy as np
import random
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
% matplotlib inline
sns.set()

In [8]:
names = ["Area", "Perimeter", "Compactness", "Length", "Width", "Asymmetry", "Groove", "Seed"]

df = pd.read_csv('../../data/seeds_dataset.txt', delim_whitespace=True, names = names)

### Treinamento

In [9]:
X = df.drop('Seed', axis=1)
y = df['Seed']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [15]:
rate  = [0.01, 0.05]
epoch = 50
a     = [0.5, 2, 3]

max_iter   = [1000, 2000,  2500]
neuron_out = np.arange(1, 15)
neuron_ini = np.arange(1, 15)
activation_functions = ['relu', 'logistic', 'identity']

In [16]:
list_prediction = []

In [18]:
for i in range(5):
    ai  = random.choice(a)
    ni  = random.choice(neuron_ini)
    no  = random.choice(neuron_out)

    nh  = ai*np.sqrt((ni*no))

    parameters = dict([
                    ('max_iter', max_iter),
                    ('hidden_layer_sizes', (no,)),
                    ('learning_rate_init', rate),
                    ('activation', activation_functions)
                ])

    clf = GridSearchCV(MLPClassifier(), parameters, cv = 3)
    clf.fit(X_train, y_train)
    prediction = clf.predict(X_test)

    f1score = f1_score(y_test, prediction, average = 'weighted')
    list_prediction.append([f1score, prediction])

/home/julianyraiol/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [38]:
for i in range(len(list_prediction)):
    f1score = list_prediction[i][0]
    print("\n-------------------------------------\n\n")
    print("Rede:", i, "\n")
    print("F1_SCORE: ", f1score)
    print("\nMatriz de Confusão\n")
    print(confusion_matrix(prediction, y_test))


-------------------------------------


Rede: 0 

F1_SCORE:  0.9065003779289493

Matriz de Confusão

[[17  1  4]
 [ 1 21  0]
 [ 0  0 19]]

-------------------------------------


Rede: 1 

F1_SCORE:  0.12698412698412698

Matriz de Confusão

[[17  1  4]
 [ 1 21  0]
 [ 0  0 19]]

-------------------------------------


Rede: 2 

F1_SCORE:  0.9065003779289493

Matriz de Confusão

[[17  1  4]
 [ 1 21  0]
 [ 0  0 19]]

-------------------------------------


Rede: 3 

F1_SCORE:  0.9065003779289493

Matriz de Confusão

[[17  1  4]
 [ 1 21  0]
 [ 0  0 19]]

-------------------------------------


Rede: 4 

F1_SCORE:  0.9065003779289493

Matriz de Confusão

[[17  1  4]
 [ 1 21  0]
 [ 0  0 19]]
